apiVersion: v1
kind: Service
metadata:
  labels: 
    app: loadgenerator
  name: loadgenerator
spec:
  ports:
  - port: 5557
    name: comm
  - port: 8089
    name: web-ui
  - port: 5558
    name: comm-plus-one
  selector:
    app: loadgenerator
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          MAX_RETRIES=12
          RETRY_INTERVAL=10
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
            if [ $STATUSCODE -eq 200 ]; then
                echo "Frontend is reachable."
                exit 0
            fi
            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
            sleep $RETRY_INTERVAL
          done
          echo "Failed to reach frontend after $MAX_RETRIES attempts."
          exit 1
        name: frontend-check
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: busybox:latest
        env:
        - name: FRONTEND_ADDR
          value: "frontend-external:80"
        
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi

      containers:
      - name: loadgenerator
        volumeMounts:
        - name: load-logs
          mountPath: /stats

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
        image: docker.io/eberkley/microservices-loadgenerator:594c8364
        imagePullPolicy: IfNotPresent
        env:
        - name: LOCUST_MODE
          value: MASTER

        - name: FRONTEND_ADDR
          value: "frontend-external:80"

        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi

        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-one
        - containerPort: 8089
          name: web-ui
      volumes:
      - name: load-logs
        emptyDir:
          sizeLimit: 300Mi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: loadgenerator-worker
  name: loadgenerator-worker
spec:
  replicas: 18
  selector:
    matchLabels:
      app: loadgenerator-worker
  template:
    metadata:
      labels:
        app: loadgenerator-worker
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          MAX_RETRIES=12
          RETRY_INTERVAL=10
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
            if [ $STATUSCODE -eq 200 ]; then
                echo "Frontend is reachable."
                exit 0
            fi
            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
            sleep $RETRY_INTERVAL
          done
          echo "Failed to reach frontend after $MAX_RETRIES attempts."
          exit 1
        name: frontend-check
        resources:
          requests:
            cpu: "1"
            memory: "1024Mi"
          limits:
            cpu: "1"
            memory: "1024Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: busybox:latest
        env:
        - name: FRONTEND_ADDR
          value: "frontend-external:80"

      containers:
      - name: loadgenerator-worker
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true


        image: docker.io/eberkley/microservices-loadgenerator:594c8364
        imagePullPolicy: IfNotPresent
        env:
        - name: LOCUST_MODE
          value: WORKER

        - name: LOCUST_MASTER
          value: loadgenerator
        
        - name: FRONTEND_ADDR
          value: "frontend:80"

        resources:
          requests:
            cpu: "1"
            memory: "1024Mi"
          limits:
            cpu: "1"
            memory: "1024Mi"